Java的基本理念是“结构不佳的代码不能运行”
异常处理是Java中唯一正式的错误报告机制，并且通过编译器强制执行。

创建自定义异常
-----------
```java
/**
 * Created by 11981 on 2017/1/2.
 */
class SimpleException extends Exception{}
public class InheritingExceptions {
    public void f() throws SimpleException{
        System.out.println("Throwing SimpleException from f()");
        throw new SimpleException();
    }
    public static void main(String[] args){
        InheritingExceptions sed = new InheritingExceptions();
        try {
            sed.f();
        }catch (SimpleException e){
            e.printStackTrace(System.out);
        }
    }

}
/*Throwing SimpleException from f()
*SimpleException
*	at InheritingExceptions.f(InheritingExceptions.java:8)
*	at InheritingExceptions.main(InheritingExceptions.java:13)
*	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
*	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
*	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
*	at java.lang.reflect.Method.invoke(Method.java:498)
*	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
*
* */

```
在异常处理程序中，调用了`Throwable`类声明的`printStackTrace()`方法。它将打印`从方法调用到异常抛出处`的方法调用序列。这里，信息被送到了System.out，并自动地被捕获和显示在输出中。如果调用默认版本

	e.printStackTrace()
	
则信息将被输出到标准输出流。

重新抛出异常
-------
重抛异常会把异常抛给上一级环境中的异常处理程序，同一个try块的后续catch子句将被忽略。此外异常对象的所有信息都得以保持，所以高一级环境中捕获此异常的处理程序可以从这个异常对象中得到所有的信息。

如果只是把异常对象重新抛出，那么`printStackTrace()`方法显示的将是原来异常抛出点的调用栈信息，并非重新抛出点的信息，要想更新这个信息，可以调用`fillInStackTrace（）`方法，这将返回一个Throwable对象。

Java标准异常
-----------
Throwable对象可以分为两种类型：

* Error 用来表示编译时和系统错误
* Exception 是可以被抛出的基本类型

首先来看`RuntimeException`，这是不需要声明，可以被自动捕获的异常。

使用finally进行清理
-----------
finally的使用场景：

* 当要把除内存之外的资源恢复到他们的初始状态时，就要用到fianlly子句。
	* 如已经打开的文件或网络连接
* 因为finally子句总是会执行的，所以在一个方法中，可以从多个点返回，并且可以保证重要的清理工作仍旧会执行。

